name: Deploy to S3
on:
push:
branches:
- main
jobs:
deploy:
runs-on: ubuntu-latest
steps:
- name: Checkout code
uses: actions/checkout@v2
- name: Deploy to S3
uses: jakejarvis/s3-sync-action@master
with:
args: --delete
env:
AWS_S3_BUCKET: your-bucket-name
AWS_ACCESS_KEY_ID: ${{AKIAQLTTCURKSQFMO65Z}}
AWS_SECRET_ACCESS_KEY: ${{Oz3haoHNsoisI9jKcLUvir0+GfJwFysW1pdNZrX/}}
AWS_REGION: us-east-1
SOURCE_DIR: "./dist" # Change to your build folder